version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: buena_postgres
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: buena
      POSTGRES_PASSWORD: password
      POSTGRES_DB: buena_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15-alpine
    container_name: buena_postgres_test
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: buena
      POSTGRES_PASSWORD: password
      POSTGRES_DB: buena_test_db
    tmpfs:
      - /var/lib/postgresql/data # faster tests, no persistence needed
